config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :image_posts
  resources :text_posts
  resources :posts
  resources :users
  resources :sessions

  get 'signup', to: 'users#new', as: 'signup'
  post 'follow/:id', to: 'users#follow', as: 'follow_user'

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  root 'posts#index'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/image_post.rb
class ImagePost < Post
	validates :url, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  validates :user_id, presence: true
  validates :type, presence: true
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :leader, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/text_post.rb
class TextPost < Post
	validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :subscriptions, foreign_key: :follower_id,
                             dependent: :destroy
	has_many :leaders, through: :subscriptions
	has_many :reverse_subscriptions, foreign_key: :leader_id,
                                     class_name: 'Subscription',
                                     dependent: :destroy
	has_many :followers, through: :reverse_subscriptions

	has_many :posts, dependent: :destroy
	has_many :text_posts, dependent: :destroy
	has_many :image_posts, dependent: :destroy 
	has_many :comments

	has_secure_password

	validates :email, presence: true, uniqueness: true

	def timeline_user_ids
      leader_ids + [id]
    end

	def following?(leader)
		leaders.include? leader
	end

	def follow!(leader)
		if leader != self && !following?(leader)
		 leaders << leader
   end
  end
 end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private 

  def current_user
    if session[:user_id]
  	  @current_user ||= User.find(session[:user_id])
   end
  end
   helper_method :current_user

  def authenticate_user!
  	redirect_to login_path unless current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/image_posts_controller.rb
class ImagePostsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!
    

	def index
      user_ids = current_user.timeline_user_ids
      @posts = Post.includes(:user).where(user_id: user_ids).order("created_at DESC")
    end

    def show
      @post = Post.find(params[:id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end


   def create
   	user = User.find_by(email: params[:email])
   	if user && user.authenticate(params[:password])
   	   session[:user_id] = user.id
   	   redirect_to root_url, notice: "Log in successful!"
   	else
   	  flash.now.alert = "Invalid email or password"
   	  render "new"
   	end
    end

   	def destroy
   		session[:user_id] = nil
   		redirect_to root_url, notice: "Log out successful!"
   	end
   end

app/controllers/text_posts_controller.rb
class TextPostsController < ApplicationController
	
    
	def new
		@text_post = TextPost.new
	end


    #The create method builds a new text post for the current user using the params from the form. 
    #If it is able to save this new post, it redirects the user Image from book to the newly created post. 
    #Otherwise, it renders the new text post form Image from book again with an error message.
	def create
       @text_post = current_user.text_posts.build(text_post_params)
     if 
       @text_post.save 
       redirect_to post_path(@text_post), 
                           notice: "Post created!"
     else 
       render :new, alert: "Error creating post."
     end
  end

  def edit
      @text_post = current_user.text_posts.find(params[:id])
  end

  def update
      @text_post = current_user.text_posts.find(params[:id])
      if @text_post.update(text_post_params)
        redirect_to post_path(@text_post), notice: "Post updated!"
      else
        render :edit, alert: "Error updating post."
      end
  end

    private 
     def text_post_params 
       params.require(:text_post).permit(:title, :body)
     end

end

  

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
    end

    def create
    	@user = User.new(user_params)
    	if @user.save
        redirect_to root_url,
         notice: "Welcome to the site!"
        else
         render "new"
       end
    end
    
    #method to show all of a users posts,
    #find user using user id
    #show posts by date create in descending order
    def show 
        @user = User.find(params[:id])
        @posts = @user.posts.order("created_at DESC")
    end

    def follow
        @user = User.find(params[:id])
        if current_user.follow!(@user)
            redirect_to @user, notice: "Follow successful!"
        else
            redirect_to @user, alert: "Error following."
        end
    end

    private

    def user_params
    	params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/image_posts_helper.rb
module ImagePostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/text_posts_helper.rb
module TextPostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/image_posts/_image_post.html.erb
<div class="panel panel-default">
 <div class="panel heading">
  <h3 class="panel-title">
  	<%= image_post.title %>
  </h3>
 </div>

 <div class="panel panel-body">
  <p><em>By <%= image_post.user.name %></em></p>

  <%= image_tag image_post.url, class: "img-responsive" %>

  <%= image_post.body %>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Social</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

 <div class="container">
 	<body>
     <div class="container">
      <% if notice %>
       <div class="alert alert-success"><%= notice %></div>
      <% end %>
      <% if alert %>
       <div class="alert alert-danger"><%= alert %></div>
      <% end %>

  <div class="pull-right">
   <% if current_user %>
    <%= link_to 'Log Out', logout_path %>
   <% else %>
    <%= link_to 'Log In', login_path %>
    or
    <%= link_to 'Sign Up', signup_path %>
  <% end %>
</div>



<%= yield %>

 </div>

</body>
</html>

app/views/posts/index.html.erb
<div class="page-header">

 <p>
  <%= link_to "New Text Post", new_text_post_path, class: "btn btn-default" %>
 </p>

 <h1>Home</h1>

</div>

<%= render @posts %>

app/views/posts/show.html.erb
<div class="page-header">

 <h1>Post</h1>

</div>

<%= render @post %>

<%= link_to "Home", posts_path, class: "btn btn-default" %>

app/views/text_posts/_form.html.erb
<%= form_for @text_post do |f| %>
  <div class = "form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class = "form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
  <%= link_to 'Cancel', :back, class: "btn btn-default" %>
<% end %> 

app/views/text_posts/_text_post.html.erb
<div class="panel panel-default">
 <div class="panel heading">
  <h3 class="panel-title">
  	<%= text_post.title %>
  </h3>
 </div>

 <div class="panel panel-body">
  <p><em>By <%= text_post.user.name %></em></p>

  <%= text_post.body %>

  <% if text_post.user == current_user %>
   <p>
   <%= link_to 'Edit', edit_text_post_path(text_post), class: "btn btn-default" %>
   </p>

   <% end %>
  
 </div>
</div>

app/views/text_posts/edit.html.erb
<div class = "page-header">
  <h1>Edit Post</h1>
</div>
    
<%= render 'form' %> 

app/views/text_posts/new.html.erb
<div class = "page-header">
  <h1>New Text Post</h1>
</div>

<%= render 'form' %>

app/views/users/new.html.erb
  <div class="page-header">
     <h1>Sign Up</h1>
   </div>

   <%= form_for(@user) do |f| %>
     <% if @user.errors.any? %>
       <div class="alert alert-danger">
         <strong>
           <%= pluralize(@user.errors.count, "error") %>
           prevented you from signing up:
         </strong>
         <ul>
           <% @user.errors.full_messages.each do |msg| %>
             <li><%= msg %></li>
           <% end %>
         </ul>
       </div>
     <% end %>

    <div class="form-group">
       <%= f.label :email %>
       <%= f.email_field :email, class: "form-control" %>
     </div>
     <div class="form-group">
       <%= f.label :password %>
       <%= f.password_field :password, class: "form-control" %>
     </div>
     <div class="form-group">
       <%= f.label :password_confirmation %>
       <%= f.password_field :password_confirmation,
       class: "form-control" %>
     </div>

     <%= f.submit class: "btn btn-primary" %>
   <% end %>

app/views/users/show.html.erb
<div class = "page-header">
   <h1>User</h1>
</div>

<p class = "lead"><%= @user.name %></p>

<%= link_to "Follow", follower_user_path(@user), method: :post, class: "btn btn-default" %>

<h2>Posts</h2>

<%= render @posts %>

<%= link_to "Home", root_path, class: "btn btn-default" %>